[package]
name = "blink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv-rt = "0.9.0"
riscv = "0.8.0"
panic-halt = "0.2.0"

[dependencies.hpm6750-rs]
path = "../hpm6750-rs"
features = ["rt"]
